In [ ]:
Part 1: Theoretical Queltions
Q1 What are the different data structures used in Tensorflow?. Give some examples.
ans:
TensorFlow provides several data structures that are commonly used for building and working with deep learning models. Some of the key data structures in TensorFlow
are:

Tensors: Tensors are the fundamental data structures in TensorFlow. They are multi-dimensional arrays of fixed-size homogeneous elements. Tensors can have any 
number of dimensions (rank) and store numerical data. Tensors are used to represent inputs, outputs, and intermediate values in a TensorFlow computation graph.

Constants: Constants are tensors whose values cannot be changed once defined. They are used to store fixed values such as hyperparameters, model architecture, or
any other constant values required in the computation. Constants are typically used to store weights, biases, or other non-trainable parameters.

Variables: Variables are tensors whose values can be updated during training. They are commonly used to store the learnable parameters of a deep learning model, 
such as the weights and biases. Variables allow the model to learn and adapt its parameters based on the training data. Unlike constants, the values of variables
can be modified using operations like gradient descent during optimization.

Placeholders: Placeholders are used to feed actual data into a TensorFlow computation graph during runtime. They are used when the actual values are not known at 
the time of defining the computation graph, such as during model training or inference. Placeholders act as input nodes and are filled with data using a feed 
dictionary or the feed_dict argument during the execution of a TensorFlow session.

In [ ]:
Q2 How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.
ans:
In TensorFlow, a constant is a type of tensor whose value remains constant throughout the execution of a computation graph. It cannot be modified once defined. On
the other hand, a variable is a type of tensor that holds a value that can be changed during the execution of a computation graph, typically during training. Here's
an example to illustrate the difference:

import tensorflow as tf

# TensorFlow constant
constant = tf.constant(5.0)
print(constant)  
# Tensor("Const:0", shape=(), dtype=float32)

# TensorFlow variable
variable = tf.Variable(2.0)
print(variable)  
# <tf.Variable 'Variable:0' shape=() dtype=float32_ref>

In the above example, we create a TensorFlow constant with a value of 5.0 using tf.constant(). The constant tensor cannot be modified, and its value remains fixed 
throughout the execution.

Next, we create a TensorFlow variable with an initial value of 2.0 using tf.Variable(). Variables are typically used to hold the learnable parameters of a model. 
Unlike constants, the value of a variable can be updated during training using optimization algorithms like gradient descent.

In [ ]:
Q3 Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.
ans:
In TensorFlow, matrix addition, multiplication, and element-wise operations can be performed using various functions and operators. Here's a description of each:

1. Matrix Addition: In TensorFlow, matrix addition can be performed using the tf.add() function or the + operator. It requires the matrices to have the same shape. 
For example:
    import tensorflow as tf

matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Matrix addition using tf.add()
result = tf.add(matrix1, matrix2)
print(result.numpy())  
# [[6  8], [10 12]]

# Matrix addition using +
result = matrix1 + matrix2
print(result.numpy())  
# [[6  8], [10 12]]

2. Matrix Multiplication: TensorFlow provides the tf.matmul() function to perform matrix multiplication. The function requires the inner dimensions of the matrices 
to match. For element-wise multiplication, you can use the * operator. For example:
import tensorflow as tf

matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Matrix multiplication using tf.matmul()
result = tf.matmul(matrix1, matrix2)
print(result.numpy())  
# [[19 22], [43 50]]

# Element-wise multiplication using *
result = matrix1 * matrix2
print(result.numpy())  
# [[5 12], [21 32]]

3. Element-wise Operations: TensorFlow provides element-wise operations for tensors, which perform element-wise computations between tensors of the same shape. 
These operations include addition (tf.add() or +), subtraction (tf.subtract() or -), multiplication (tf.multiply() or *), division (tf.divide() or /), 
exponentiation (tf.pow() or **), and more. For example:
import tensorflow as tf

tensor1 = tf.constant([1, 2, 3])
tensor2 = tf.constant([4, 5, 6])

# Element-wise addition using tf.add()
result = tf.add(tensor1, tensor2)
print(result.numpy())  
# [5 7 9]

In [ ]:
Part 2: Practical Implementation
# Task 1: Creating and Manipulating Matricek
Q1 Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the
values of matrix A.
Q2 Create a Gaussian matrix B with dimensions x, using TensorFlow's truncated_normal function. Display
the values of matrix B.
Q3 Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a
mean of 2 and a standard deviation of 0.x, using TensorFlow's random.normal function. Display the values
of matrix C.
Q4 Perform matrix addition between matrix A and matrix B, and store the result in matrix D.
Q5 Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.
# Task 3: Performing Additional Matrix Operationk
Q6 Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform
function.
Q7 Calculate the transpose of matrix F and store the result in matrix G.
Q8 Calculate the elementDwise exponential of matrix F and store the result in matrix H.
Q9 Create a matrix I by concatenating matrix F and matrix G horizontally.
Q10 Create a matrix J by concatenating matrix F and matrix H vertically.

In [6]:
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

# Task 1
# Q1
A = tf.random.normal((2, 2))
print("Matrix A:")
print(A.numpy())

# Q2
B = tf.random.truncated_normal((2, 2))
print("Matrix B:")
print(B.numpy())

# Q3
C = tf.random.normal((2, 2), mean=2, stddev=0.1)
print("Matrix C:")
print(C.numpy())

# Q4
D = tf.add(A, B)
print("Matrix D (A + B):")
print(D.numpy())

# Q5
E = tf.matmul(C, D)
print("Matrix E (C * D):")
print(E.numpy())

# Task 3
# Q6
F = tf.random.uniform((2, 2))
print("Matrix F:")
print(F.numpy())

# Q7
G = tf.transpose(F)
print("Matrix G (Transpose of F):")
print(G.numpy())

# Q8
H = tf.exp(F)
print("Matrix H (Element-wise exponential of F):")
print(H.numpy())

# Q9
I = tf.concat([F, G], axis=1)
print("Matrix I (Horizontal concatenation of F and G):")
print(I.numpy())

# Q10
J = tf.concat([F, H], axis=0)
print("Matrix J (Vertical concatenation of F and H):")
print(J.numpy())

Matrix A:
[[ 0.36816943 -0.03331733]
 [ 0.769923    0.94038385]]
Matrix B:
[[ 1.2487755   0.25965124]
 [-1.4791055  -0.58906275]]
Matrix C:
[[2.0139601 1.9313155]
 [1.9404162 1.7967931]]
Matrix D (A + B):
[[ 1.6169449   0.22633392]
 [-0.7091825   0.3513211 ]]
Matrix E (C * D):
[[1.8868074 1.1343393]
 [1.8632919 1.0704334]]
Matrix F:
[[0.8705996  0.5669694 ]
 [0.21438289 0.47337854]]
Matrix G (Transpose of F):
[[0.8705996  0.21438289]
 [0.5669694  0.47337854]]
Matrix H (Element-wise exponential of F):
[[2.3883426 1.7629162]
 [1.239097  1.605409 ]]
Matrix I (Horizontal concatenation of F and G):
[[0.8705996  0.5669694  0.8705996  0.21438289]
 [0.21438289 0.47337854 0.5669694  0.47337854]]
Matrix J (Vertical concatenation of F and H):
[[0.8705996  0.5669694 ]
 [0.21438289 0.47337854]
 [2.3883426  1.7629162 ]
 [1.239097   1.605409  ]]
