In [8]:
# Consider the below code to answer further questions:
import numpy as np
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)

In [9]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.
ans:- Yes both variable have different data types.
array_list.dtype

dtype('<U1')

In [15]:
type(list_)

list

In [16]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

# printing the data type of each element of the list
for i in range(len(list_)):
    print(f"The data type of element {i} of list_ is {type(list_[i])}")

# printing the data type of each element of the numpy array
for i in range(len(array_list)):
    print(f"The data type of element {i} of array_list is {array_list[i].dtype}")


The data type of element 0 of list_ is <class 'str'>
The data type of element 1 of list_ is <class 'str'>
The data type of element 2 of list_ is <class 'str'>
The data type of element 3 of list_ is <class 'str'>
The data type of element 4 of list_ is <class 'str'>
The data type of element 0 of array_list is <U1
The data type of element 1 of array_list is <U1
The data type of element 2 of array_list is <U1
The data type of element 3 of array_list is <U1
The data type of element 4 of array_list is <U1


In [21]:
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_
and array_list.
ans: Yes, there will be a difference in the data type of the elements present in both variables list_ and array_list.
for i in range(len(list_)):
    print(f"The data type of element {i} of list_ is {type(list_[i])}")

# printing the data type of each element of the numpy array
for i in range(len(array_list)):
    print(f"The data type of element {i} of array_list is {array_list[i].dtype}")

The data type of element 0 of list_ is <class 'str'>
The data type of element 1 of list_ is <class 'str'>
The data type of element 2 of list_ is <class 'str'>
The data type of element 3 of list_ is <class 'str'>
The data type of element 4 of list_ is <class 'str'>
The data type of element 0 of array_list is int64
The data type of element 1 of array_list is int64
The data type of element 2 of array_list is int64
The data type of element 3 of array_list is int64
The data type of element 4 of array_list is int64


In [26]:
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
print(num_array.shape)
# (ii) size
print(num_array.size)

(2, 3)
6


In [30]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]
ans :

arr=np.zeros((3,3))
print(arr)
print(arr.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


In [32]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])